{% set name = "factur-x" %}
{% set version = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f6ebaf2b512a621ab9a77477d9aba6700f3bff495a93298d25345a46ef85cdc3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
    - hatch-requirements-txt
  run:
    - python >={{ python_min }}
    - pypdf >=5.3.0
    - lxml
    - setuptools

test:
  imports:
    - facturx
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/akretion/factur-x
  summary: 'Factur-X and Order-X: electronic invoicing and ordering standards'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
